server:
  port: 8080

spring:
  application:
    name: PersonaAI
  config:
    import: "optional:classpath:application-secret.yml"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslMode=REQUIRED&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    #   InnoDB 설정
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #   테이블 자동 생성
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 3000 # 분 단위